# base config
seed: 2023
device: 'cuda'
num_workers: 4

lr: 0.0001
lr_drop: 400
wd: 0.0001
n_epoch: 200
bsz: 32
eval_bsz: 100
grad_clip: 0.1
max_windows: 5
clip_length: 1
eval_epoch_interval: 1

position_embedding: "sine"
enc_layers: 2
dec_layers: 2
dim_feedforward: 1024
hidden_dim: 256
input_dropout: 0.5
dropout: 0.1
nheads: 8
num_queries: 10

n_input_proj: 2
saliency_margin: 0.2
span_loss_type: "l1"
set_cost_span: 10
set_cost_giou: 1
set_cost_class: 4
span_loss_coef: 10
giou_loss_coef: 1
label_loss_coef: 4
eos_coef: 0.1
lw_saliency: 1

ckpt_filename: best_checkpoint.pth
train_log_filename: train.log
eval_log_filename: val.log
eval_split_name: val
aux_loss: True

model_ema: False
ema_decay: 0.9
results_dir: results_pretraining

# clotho-moment-specific config
dset_name: clotho-moment
clip_length: 1
train_path: data/clotho_moment_train_release.jsonl
val_path: data/clotho_moment_val_release.jsonl
test_path: data/clotho_moment_test_release.jsonl
submission_path: private/dcase2026_private.jsonl
max_q_l: 32
max_a_l: 300

# feature-specific config 
ctx_mode: audio_tef
a_feat_dir: features/clotho-moment/clap
t_feat_dir: features/clotho-moment/clap_text
a_sub_feat_dir: private/feature/clap
t_sub_feat_dir: private/feature/clap_text
a_feat_type: clap
t_feat_type: clap
a_feat_dim: 768
t_feat_dim: 768

model_name: qd_detr
